"""Fixed-room M6.x contracts and executable canary support."""

from avengine.m6x.capture_adapter import (
    FixedApartmentCaptureAdapter,
    HUMAN_BEAGLE_CAPTURE_ADAPTER,
    HumanBeagleCaptureAdapter,
)
from avengine.m6x.contracts import (
    ANCHOR_LIBRARY_SCHEMA,
    M6XContractError,
    ROOM_CAPSULE_SCHEMA,
    SCENARIO_CONTRACT,
    SCENARIO_SUITE_SCHEMA,
    TRAJECTORY_TEMPLATE_SET_SCHEMA,
    load_anchor_library,
    load_room_capsule,
    load_scenario_suite,
    load_trajectory_template_set,
    validate_anchor_library,
    validate_room_capsule,
    validate_scenario_suite,
    validate_trajectory_template_set,
)
from avengine.m6x.room_feasibility import (
    FeasibleRegionIndex,
    RoomFeasibilityCompiler,
    RoomFeasibilityError,
    SOURCE_SLOTS,
    TrajectoryBank,
    TrajectoryBankBuilder,
    TrajectoryCoverage,
    build_rir_job_plan,
    evaluate_trajectory_coverage,
    evaluate_trajectory_diversity,
)
from avengine.m6x.raster_pathfinder import (
    RasterPathfinder,
    RasterPathfinderError,
    RasterShortestPath,
    build_polygon_raster_obstacle_map,
)
from avengine.m6x.rir_cache import (
    CachedRIREpisode,
    RIRBatchResult,
    RIRCacheError,
    RIRCacheResult,
    render_rir_cache,
    load_cached_rir_episode,
    validate_rir_job_plan,
)

__all__ = [
    "ANCHOR_LIBRARY_SCHEMA",
    "CachedRIREpisode",
    "FixedApartmentCaptureAdapter",
    "FeasibleRegionIndex",
    "HUMAN_BEAGLE_CAPTURE_ADAPTER",
    "HumanBeagleCaptureAdapter",
    "M6XContractError",
    "ROOM_CAPSULE_SCHEMA",
    "RasterPathfinder",
    "RasterPathfinderError",
    "RasterShortestPath",
    "RIRBatchResult",
    "RIRCacheError",
    "RIRCacheResult",
    "RoomFeasibilityCompiler",
    "RoomFeasibilityError",
    "SCENARIO_CONTRACT",
    "SCENARIO_SUITE_SCHEMA",
    "SOURCE_SLOTS",
    "TRAJECTORY_TEMPLATE_SET_SCHEMA",
    "TrajectoryBank",
    "TrajectoryBankBuilder",
    "TrajectoryCoverage",
    "build_rir_job_plan",
    "build_polygon_raster_obstacle_map",
    "evaluate_trajectory_coverage",
    "evaluate_trajectory_diversity",
    "load_anchor_library",
    "load_cached_rir_episode",
    "load_room_capsule",
    "load_scenario_suite",
    "load_trajectory_template_set",
    "render_rir_cache",
    "validate_anchor_library",
    "validate_room_capsule",
    "validate_scenario_suite",
    "validate_trajectory_template_set",
    "validate_rir_job_plan",
]
